#!/usr/bin/env bash
# Dispaly 'To infinity and beyond'
# with a sleep 2in btn each iteration
# 'I am invincible!!!' when receiving a 'SIGTERM' signal

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible" ' SIGTERM
done
