#!/usr/bin/env bash
ash script that loops from 1 to 10 and:

$n=1
while [ n -le 10 ]
do
  echo "Best School"
  if [ $n -eq 4 ]
  then
    echo "bad luck"
  elif [ $n -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  n=$(( n + 1 ))
done
