#!/usr/bin/env bash
# Superstitious numbers

n=1
while [ $n -le 20 ]
do
  echo $n
  case in $n
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
    *)
      ;;
    esca
    n=$(( n + 1))
done
