#!/usr/bin/env bash
# displays the content of the current directory in a certain format

list=$(ls)
for file in $list
do
  if [[ ! "$file" == . * && "$file" == *-*]];
  then
  find "$file" | cut -d- -f2
done
