#!/usr/bin/env bash
# displays the content of the current directory in a certain format

list=$(ls)

for file in list 
do
    # Check if the file is not hidden and has a dash in the name
    if [[ ! "$file" == .* && "$file" == *-* ]]
    then
	    find "$file" | cut -d- -f2
     fi
done

