#!/usr/bin/env bash
# Bash script that gives you information about the school file.

filename="School"
if [ -e $filename ]
then
  echo "school file exists"
  if [ -s $filename ]
  then
    echo "School file is not empty"
  else
    echo "Schoolfile is empty"
  fi
  if [ -f $filename ]
    then
        echo "School is a regular file"
    fi
else
    echo "School file does not exist"
fi
